-- MySQL Script generated by MySQL Workbench
-- Mon May 18 16:56:14 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Imagens` (
  `id_imagem` INT NOT NULL AUTO_INCREMENT,
  `anexo` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id_imagem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Senha` (
  `id_senha` INT NOT NULL AUTO_INCREMENT,
  `senha_hash` VARCHAR(256) NOT NULL,
  `autenticado` TINYINT NOT NULL,
  `data_alteracao` DATETIME NULL,
  `tipo_conta` ENUM('Empregado', 'Usuario') NOT NULL,
  PRIMARY KEY (`id_senha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `ddd` INT(2) NOT NULL,
  `numero` INT(9) NOT NULL,
  `autenticado` TINYINT NOT NULL,
  `data_alteracao` DATETIME NULL,
  `tipo_conta` ENUM('Empregado', 'Usuário') NOT NULL,
  PRIMARY KEY (`id_telefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Email` (
  `id_email` INT NOT NULL AUTO_INCREMENT,
  `endereco_email` VARCHAR(150) NOT NULL,
  `verificarAutenticacao` TINYINT NOT NULL,
  `data_alteracao` DATETIME NULL,
  `tipo_conta` ENUM('Empregado', 'Usuário') NOT NULL,
  PRIMARY KEY (`id_email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_Física`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_Física` (
  `id_pessoa_fisica` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_pessoa_fisica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_Jurídica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_Jurídica` (
  `id_pessoa_juridica` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_pessoa_juridica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Pessoa` (
  `id_tipo_pessoa` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('Física', 'Jurídica') NOT NULL,
  `fk_pessoa_juridica` INT NULL,
  `fk_pessoa_fisica` INT NULL,
  PRIMARY KEY (`id_tipo_pessoa`),
  INDEX `fk_pessoa_fisica_idx` (`fk_pessoa_fisica` ASC) VISIBLE,
  INDEX `fk_pessoa_juridica_idx` (`fk_pessoa_juridica` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_fisica`
    FOREIGN KEY (`fk_pessoa_fisica`)
    REFERENCES `mydb`.`Pessoa_Física` (`id_pessoa_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_juridica`
    FOREIGN KEY (`fk_pessoa_juridica`)
    REFERENCES `mydb`.`Pessoa_Jurídica` (`id_pessoa_juridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_nascimneto` DATE NOT NULL,
  `tipo_usuario` ENUM('Cliente', 'Empregado', 'FoodService') NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `fk_imagem` INT NOT NULL,
  `fk_senha` INT NOT NULL,
  `fk_telefone` INT NOT NULL,
  `fk_email` INT NOT NULL,
  `fk_tipo_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_imagem_idx` (`fk_imagem` ASC) VISIBLE,
  INDEX `fk_senha_idx` (`fk_senha` ASC) VISIBLE,
  INDEX `fk_telefone_idx` (`fk_telefone` ASC) VISIBLE,
  INDEX `fk_email_idx` (`fk_email` ASC) VISIBLE,
  INDEX `fk_tipo_pessoa_idx` (`fk_tipo_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_imagem`
    FOREIGN KEY (`fk_imagem`)
    REFERENCES `mydb`.`Imagens` (`id_imagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_senha`
    FOREIGN KEY (`fk_senha`)
    REFERENCES `mydb`.`Senha` (`id_senha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefone`
    FOREIGN KEY (`fk_telefone`)
    REFERENCES `mydb`.`Telefone` (`id_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email`
    FOREIGN KEY (`fk_email`)
    REFERENCES `mydb`.`Email` (`id_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_pessoa`
    FOREIGN KEY (`fk_tipo_pessoa`)
    REFERENCES `mydb`.`Tipo_Pessoa` (`id_tipo_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfil` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL,
  `fk_imagem` INT NOT NULL,
  PRIMARY KEY (`id_perfil`),
  INDEX `fk_imagem_idx` (`fk_imagem` ASC) VISIBLE,
  CONSTRAINT `fk_imagem`
    FOREIGN KEY (`fk_imagem`)
    REFERENCES `mydb`.`Imagens` (`id_imagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ofício`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ofício` (
  `id_oficio` INT NOT NULL AUTO_INCREMENT,
  `nome_oficio` VARCHAR(45) NOT NULL,
  `categoria` ENUM(' ') NOT NULL,
  PRIMARY KEY (`id_oficio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lista Serviços`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lista Serviços` (
  `id_lista_servicos` INT NOT NULL AUTO_INCREMENT,
  `nome_servico` VARCHAR(45) NOT NULL,
  `detalhes_servico` VARCHAR(250) NOT NULL,
  `valor` DECIMAL NOT NULL,
  `fk_oficio` INT NOT NULL,
  `tipo_servico` ENUM('Entrega', 'Instalação') NOT NULL,
  PRIMARY KEY (`id_lista_servicos`),
  INDEX `fk_oficio_idx` (`fk_oficio` ASC) VISIBLE,
  CONSTRAINT `fk_oficio`
    FOREIGN KEY (`fk_oficio`)
    REFERENCES `mydb`.`Ofício` (`id_oficio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Status` (
  `id_status` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profissional` (
  `id_profissional` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_nascimneto` DATE NOT NULL,
  `função` ENUM('') NOT NULL,
  `data_admissao` DATETIME NOT NULL,
  `fk_perfil` INT NOT NULL,
  `fk_senha` INT NOT NULL,
  `fk_email` INT NOT NULL,
  `fk_telefone` INT NOT NULL,
  `fk_tipo_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_profissional`),
  INDEX `fk_perfil_idx` (`fk_perfil` ASC) VISIBLE,
  INDEX `fk_senha_idx` (`fk_senha` ASC) VISIBLE,
  INDEX `fk_email_idx` (`fk_email` ASC) VISIBLE,
  INDEX `fk_telefone_idx` (`fk_telefone` ASC) VISIBLE,
  INDEX `fk_tipo_pessoa_idx` (`fk_tipo_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_perfil`
    FOREIGN KEY (`fk_perfil`)
    REFERENCES `mydb`.`Perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_senha`
    FOREIGN KEY (`fk_senha`)
    REFERENCES `mydb`.`Senha` (`id_senha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email`
    FOREIGN KEY (`fk_email`)
    REFERENCES `mydb`.`Email` (`id_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefone`
    FOREIGN KEY (`fk_telefone`)
    REFERENCES `mydb`.`Telefone` (`id_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_pessoa`
    FOREIGN KEY (`fk_tipo_pessoa`)
    REFERENCES `mydb`.`Tipo_Pessoa` (`id_tipo_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitação_Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solicitação_Serviço` (
  `id_solicitacao` INT NOT NULL AUTO_INCREMENT,
  `data_solicitacao` DATETIME NOT NULL,
  `data_aceite` DATETIME NOT NULL,
  `data_finalizacao` DATETIME NOT NULL,
  `valor_final` DECIMAL NOT NULL,
  `fk_status` INT NOT NULL,
  `fk_usuario` INT NOT NULL,
  `fk_profissional` INT NOT NULL,
  PRIMARY KEY (`id_solicitacao`),
  INDEX `fk_status_idx` (`fk_status` ASC) VISIBLE,
  INDEX `fk_usuario_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_empregado_idx` (`fk_profissional` ASC) VISIBLE,
  CONSTRAINT `fk_status`
    FOREIGN KEY (`fk_status`)
    REFERENCES `mydb`.`Status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profissional`
    FOREIGN KEY (`fk_profissional`)
    REFERENCES `mydb`.`Profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serviço Solicitado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço Solicitado` (
  `id_solicitado` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL,
  `quantidade` INT NOT NULL,
  `prazo_max` DATETIME NOT NULL,
  `fk_lista_servicos` INT NOT NULL,
  `fk_solicitacao` INT NOT NULL,
  `prioridade` ENUM('Baixa', 'Média', 'Alta') NOT NULL,
  PRIMARY KEY (`id_solicitado`),
  INDEX `fk_lista_servicos_idx` (`fk_lista_servicos` ASC) VISIBLE,
  INDEX `fk_solicitacao_idx` (`fk_solicitacao` ASC) VISIBLE,
  CONSTRAINT `fk_lista_servicos`
    FOREIGN KEY (`fk_lista_servicos`)
    REFERENCES `mydb`.`Lista Serviços` (`id_lista_servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao`
    FOREIGN KEY (`fk_solicitacao`)
    REFERENCES `mydb`.`Solicitação_Serviço` (`id_solicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avaliação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avaliação` (
  `id_avaliacao` INT NOT NULL AUTO_INCREMENT,
  `estrelas` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(250) NULL,
  `data_avaliacao` DATETIME NOT NULL,
  `fk_solicitado` INT NOT NULL,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`id_avaliacao`),
  INDEX `fk_usuario_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_solicitado_idx` (`fk_solicitado` ASC) VISIBLE,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitado`
    FOREIGN KEY (`fk_solicitado`)
    REFERENCES `mydb`.`Serviço Solicitado` (`id_solicitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Postagem` (
  `id_postagem` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL,
  `data` DATETIME NOT NULL,
  `fk_perfil` INT NOT NULL,
  `fk_imagem` INT NOT NULL,
  PRIMARY KEY (`id_postagem`),
  INDEX `fk_perfil_idx` (`fk_perfil` ASC) VISIBLE,
  INDEX `fk_imagem_idx` (`fk_imagem` ASC) VISIBLE,
  CONSTRAINT `fk_perfil`
    FOREIGN KEY (`fk_perfil`)
    REFERENCES `mydb`.`Perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imagem`
    FOREIGN KEY (`fk_imagem`)
    REFERENCES `mydb`.`Imagens` (`id_imagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nome_estado` VARCHAR(45) NOT NULL,
  `sigla_estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(45) NOT NULL,
  `fk_estado` INT NOT NULL,
  PRIMARY KEY (`id_cidade`),
  INDEX `fk_estado_idx` (`fk_estado` ASC) VISIBLE,
  CONSTRAINT `fk_estado`
    FOREIGN KEY (`fk_estado`)
    REFERENCES `mydb`.`Estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereço` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(75) NULL,
  `bairro` VARCHAR(75) NOT NULL,
  `fk_cidade` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_cidade_idx` (`fk_cidade` ASC) VISIBLE,
  CONSTRAINT `fk_cidade`
    FOREIGN KEY (`fk_cidade`)
    REFERENCES `mydb`.`Cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente Endereço` (
  `fk_usuario` INT NOT NULL,
  `fk_endereco` INT NOT NULL,
  `apelido_endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`fk_usuario`, `fk_endereco`),
  INDEX `fk_endereco_idx` (`fk_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco`
    FOREIGN KEY (`fk_endereco`)
    REFERENCES `mydb`.`Endereço` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `id_entrega` INT NOT NULL AUTO_INCREMENT,
  `tipo_entrega` ENUM('Retirada, Entrega, Execução, Ambos') NOT NULL,
  `forma` ENUM('Cliente Busca', 'Empregado Entrega') NOT NULL,
  `data_entrega` DATETIME NOT NULL,
  `data_prevista` DATETIME NOT NULL,
  `fk_status` INT NOT NULL,
  `fk_solicitado` INT NOT NULL,
  PRIMARY KEY (`id_entrega`),
  INDEX `fk_solicitado_idx` (`fk_solicitado` ASC) VISIBLE,
  INDEX `fk_status_idx` (`fk_status` ASC) VISIBLE,
  CONSTRAINT `fk_solicitado`
    FOREIGN KEY (`fk_solicitado`)
    REFERENCES `mydb`.`Serviço Solicitado` (`id_solicitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_status`
    FOREIGN KEY (`fk_status`)
    REFERENCES `mydb`.`Status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profissional_Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profissional_Serviço` (
  `id_profissional` INT NOT NULL AUTO_INCREMENT,
  `fk_solicitado` INT NOT NULL,
  `fk_profissional` INT NOT NULL,
  PRIMARY KEY (`id_profissional`),
  INDEX `fk_solicitado_idx` (`fk_solicitado` ASC) VISIBLE,
  INDEX `fk_empregado_idx` (`fk_profissional` ASC) VISIBLE,
  CONSTRAINT `fk_solicitado`
    FOREIGN KEY (`fk_solicitado`)
    REFERENCES `mydb`.`Serviço Solicitado` (`id_solicitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profissional`
    FOREIGN KEY (`fk_profissional`)
    REFERENCES `mydb`.`Profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento_Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento_Serviço` (
  `id_pagamento` INT NOT NULL,
  `valor_total` DECIMAL NOT NULL,
  `metodo` ENUM('Pix', 'Cartão', 'Boleto', 'Dinheiro') NOT NULL,
  `data_pagamento` DATETIME NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `anexo_nf` MEDIUMBLOB NOT NULL,
  `fk_solicitacao` INT NOT NULL,
  `fk_status` INT NOT NULL,
  PRIMARY KEY (`id_pagamento`),
  INDEX `fk_solicitacao_idx` (`fk_solicitacao` ASC) VISIBLE,
  INDEX `fk_status_idx` (`fk_status` ASC) VISIBLE,
  CONSTRAINT `fk_solicitacao`
    FOREIGN KEY (`fk_solicitacao`)
    REFERENCES `mydb`.`Solicitação_Serviço` (`id_solicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_status`
    FOREIGN KEY (`fk_status`)
    REFERENCES `mydb`.`Status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chat` (
  `id_chat` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATETIME NOT NULL,
  `data_encerramento` DATETIME NOT NULL,
  `fk_usuario` INT NOT NULL,
  `fk_profissional` INT NOT NULL,
  `fk_Solicitacao_Servico` INT NOT NULL,
  PRIMARY KEY (`id_chat`),
  INDEX `fk_empregado_idx` (`fk_profissional` ASC) VISIBLE,
  INDEX `fk_usuario_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_Solicitacao_Servico_idx` (`fk_Solicitacao_Servico` ASC) VISIBLE,
  CONSTRAINT `fk_profissional`
    FOREIGN KEY (`fk_profissional`)
    REFERENCES `mydb`.`Profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_servico`
    FOREIGN KEY (`fk_Solicitacao_Servico`)
    REFERENCES `mydb`.`Solicitação_Serviço` (`id_solicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Arquivos Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Arquivos Chat` (
  `id_arquivo` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('Imagem', 'Audio', 'Documento', 'Vídeo') NOT NULL,
  `arquivo` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id_arquivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Remetente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Remetente` (
  `id_Remetente` INT NOT NULL,
  `fk_usuario` INT NOT NULL,
  `fk_profissional` INT NOT NULL,
  INDEX `fk_usuario_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_empregado_idx` (`fk_profissional` ASC) VISIBLE,
  PRIMARY KEY (`id_Remetente`),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profissional`
    FOREIGN KEY (`fk_profissional`)
    REFERENCES `mydb`.`Profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mensagens` (
  `id_mensagem` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('Texto', 'Imagem', 'Audio', 'Documento') NOT NULL,
  `conteudo_texto` VARCHAR(1000) NULL,
  `data_envio` DATETIME NOT NULL,
  `fk_arquivo` INT NOT NULL,
  `fk_chat` INT NOT NULL,
  `fk_remetente` INT NOT NULL,
  PRIMARY KEY (`id_mensagem`),
  INDEX `fk_arquivo_idx` (`fk_arquivo` ASC) VISIBLE,
  INDEX `fk_chat_idx` (`fk_chat` ASC) VISIBLE,
  INDEX `fk_remetente_idx` (`fk_remetente` ASC) VISIBLE,
  CONSTRAINT `fk_arquivo`
    FOREIGN KEY (`fk_arquivo`)
    REFERENCES `mydb`.`Arquivos Chat` (`id_arquivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat`
    FOREIGN KEY (`fk_chat`)
    REFERENCES `mydb`.`Chat` (`id_chat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_remetente`
    FOREIGN KEY (`fk_remetente`)
    REFERENCES `mydb`.`Remetente` (`id_Remetente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reembolso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reembolso` (
  `id_reembolso` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL NOT NULL,
  `motivo` VARCHAR(255) NOT NULL,
  `data_solicitacao` DATETIME NOT NULL,
  `data_reembolso` DATETIME NOT NULL,
  `tipo` ENUM('Integral', 'Parcial') NOT NULL,
  `fk_status` INT NOT NULL,
  `fk_pagamento` INT NOT NULL,
  PRIMARY KEY (`id_reembolso`),
  INDEX `fk_pagamento_idx` (`fk_pagamento` ASC) VISIBLE,
  INDEX `fk_status_idx` (`fk_status` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento`
    FOREIGN KEY (`fk_pagamento`)
    REFERENCES `mydb`.`Pagamento_Serviço` (`id_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_status`
    FOREIGN KEY (`fk_status`)
    REFERENCES `mydb`.`Status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agenda` (
  `id_agenda` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `fk_profissional` INT NOT NULL,
  `fk_status` INT NOT NULL,
  `fk_solicitacao` INT NOT NULL,
  PRIMARY KEY (`id_agenda`),
  INDEX `fk_status_idx` (`fk_status` ASC) VISIBLE,
  INDEX `fk_empregado_idx` (`fk_profissional` ASC) VISIBLE,
  INDEX `fk_solicitacao_idx` (`fk_solicitacao` ASC) VISIBLE,
  CONSTRAINT `fk_status`
    FOREIGN KEY (`fk_status`)
    REFERENCES `mydb`.`Status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profissional`
    FOREIGN KEY (`fk_profissional`)
    REFERENCES `mydb`.`Profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao`
    FOREIGN KEY (`fk_solicitacao`)
    REFERENCES `mydb`.`Solicitação_Serviço` (`id_solicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parcelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parcelas` (
  `id_parcela` INT NOT NULL AUTO_INCREMENT,
  `numero_parcela` INT NOT NULL,
  `valor` DECIMAL NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `data_pagamento` DATETIME NOT NULL,
  `fk_pagamento` INT NOT NULL,
  `fk_status` INT NOT NULL,
  PRIMARY KEY (`id_parcela`),
  INDEX `fk_pagamento_idx` (`fk_pagamento` ASC) VISIBLE,
  INDEX `fk_status_idx` (`fk_status` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento`
    FOREIGN KEY (`fk_pagamento`)
    REFERENCES `mydb`.`Pagamento_Serviço` (`id_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_status`
    FOREIGN KEY (`fk_status`)
    REFERENCES `mydb`.`Status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Documentos` (
  `id_documento` INT NOT NULL,
  `nome_documento` VARCHAR(45) NOT NULL,
  `tipo` ENUM('') NOT NULL,
  `anexo` MEDIUMBLOB NOT NULL,
  `fk_profissional` INT NOT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `fk_empregado_idx` (`fk_profissional` ASC) VISIBLE,
  CONSTRAINT `fk_profissional`
    FOREIGN KEY (`fk_profissional`)
    REFERENCES `mydb`.`Profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chat_Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chat_Serviço` (
  `fk_solicitacao` INT NULL,
  `fk_chat` INT NULL,
  INDEX `fk_chat_idx` (`fk_chat` ASC) VISIBLE,
  INDEX `fk_solicitacao_idx` (`fk_solicitacao` ASC) VISIBLE,
  PRIMARY KEY (`fk_chat`, `fk_solicitacao`),
  CONSTRAINT `fk_chat`
    FOREIGN KEY (`fk_chat`)
    REFERENCES `mydb`.`Chat` (`id_chat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao`
    FOREIGN KEY (`fk_solicitacao`)
    REFERENCES `mydb`.`Solicitação_Serviço` (`id_solicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Denunciador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Denunciador` (
  `id_denunciador` INT NOT NULL AUTO_INCREMENT,
  `fk_usuario` INT NULL,
  `fk_profissional` INT NULL,
  PRIMARY KEY (`id_denunciador`),
  INDEX `fk_usuario_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_profissional_idx` (`fk_profissional` ASC) VISIBLE,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profissional`
    FOREIGN KEY (`fk_profissional`)
    REFERENCES `mydb`.`Profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Arquivos Prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Arquivos Prova` (
  `id_arquivo_prova` INT NOT NULL AUTO_INCREMENT,
  `anexo` VARCHAR(45) NOT NULL,
  `tipo` ENUM('Imagem', 'Audio', 'Documento', 'Vídeo') NOT NULL,
  PRIMARY KEY (`id_arquivo_prova`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Denúncias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Denúncias` (
  `id_denuncia` INT NOT NULL,
  `motivo` VARCHAR(255) NOT NULL,
  `data_denuncia` DATETIME NOT NULL,
  `data_finalizacao` DATETIME NULL,
  `fk_usuario` INT NOT NULL,
  `fk_profissional` INT NOT NULL,
  `fk_denunciador` INT NOT NULL,
  `fk_arquivo_prova` INT NULL,
  `fk_status` INT NOT NULL,
  PRIMARY KEY (`id_denuncia`),
  INDEX `fk_profissional_idx` (`fk_profissional` ASC) VISIBLE,
  INDEX `fk_usuario_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_denunciador_idx` (`fk_denunciador` ASC) VISIBLE,
  INDEX `fk_anexo_prova_idx` (`fk_arquivo_prova` ASC) VISIBLE,
  INDEX `fk_status_idx` (`fk_status` ASC) VISIBLE,
  CONSTRAINT `fk_profissional`
    FOREIGN KEY (`fk_profissional`)
    REFERENCES `mydb`.`Profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_denunciador`
    FOREIGN KEY (`fk_denunciador`)
    REFERENCES `mydb`.`Denunciador` (`id_denunciador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arquivo_prova`
    FOREIGN KEY (`fk_arquivo_prova`)
    REFERENCES `mydb`.`Arquivos Prova` (`id_arquivo_prova`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_status`
    FOREIGN KEY (`fk_status`)
    REFERENCES `mydb`.`Status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
