-- ==============================================================================
-- Migration: Criação de lista_servicos, ass_servicos_lista e modificação de solicitacoes
-- Execute este script no SQL Editor do Supabase.
-- ==============================================================================

-- 1. Criação da tabela 'lista_servicos'
CREATE TABLE IF NOT EXISTS public.lista_servicos (
    id_lista bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_usuario bigint NOT NULL,
    valor_total numeric NOT NULL DEFAULT 0,
    data_criacao timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT lista_servicos_pkey PRIMARY KEY (id_lista),
    CONSTRAINT lista_servicos_fk_usuario_fkey FOREIGN KEY (fk_usuario)
        REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE
);

ALTER TABLE public.lista_servicos
    ADD COLUMN IF NOT EXISTS valor_total numeric NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS lista_servicos_fk_usuario_idx
    ON public.lista_servicos (fk_usuario);

-- 2. Criação da tabela associativa 'ass_servicos_lista'
CREATE TABLE IF NOT EXISTS public.ass_servicos_lista (
    fk_lista bigint NOT NULL,
    fk_servico_prof bigint NOT NULL,
    valor_final numeric NOT NULL,
    tipo_execucao_escolhido text NOT NULL,
    fk_endereco_escolhido bigint,
    detalhes text,
    data_agendada date NOT NULL,
    hora_agendada time without time zone NOT NULL,
    data_criacao timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ass_servicos_lista_pkey PRIMARY KEY (fk_lista, fk_servico_prof),
    CONSTRAINT ass_servicos_lista_fk_lista_fkey FOREIGN KEY (fk_lista)
        REFERENCES public.lista_servicos(id_lista) ON DELETE CASCADE,
    CONSTRAINT ass_servicos_lista_fk_servico_prof_fkey FOREIGN KEY (fk_servico_prof)
        REFERENCES public.servicos_profissional(id_servico_prof) ON DELETE CASCADE,
    CONSTRAINT ass_servicos_lista_fk_endereco_escolhido_fkey FOREIGN KEY (fk_endereco_escolhido)
        REFERENCES public.enderecos(id_endereco) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ass_servicos_lista_fk_lista_idx
    ON public.ass_servicos_lista (fk_lista);

CREATE INDEX IF NOT EXISTS ass_servicos_lista_fk_servico_prof_idx
    ON public.ass_servicos_lista (fk_servico_prof);

-- 3. Modificação da tabela 'solicitacoes'
-- Remove gatilho legado se existir (pois dependia de colunas como fk_servico_prof ou tipo_entrega)
DROP TRIGGER IF EXISTS validar_tipo_entrega_solicitacao_trigger ON public.solicitacoes;

-- Garante que as colunas solicitadas existam
ALTER TABLE public.solicitacoes
    ADD COLUMN IF NOT EXISTS data_solicitacao timestamp with time zone NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS data_aceite timestamp with time zone,
    ADD COLUMN IF NOT EXISTS valor_final numeric,
    ADD COLUMN IF NOT EXISTS fk_usuario bigint,
    ADD COLUMN IF NOT EXISTS fk_profissional bigint,
    ADD COLUMN IF NOT EXISTS fk_status bigint,
    ADD COLUMN IF NOT EXISTS fk_grupo_empresa bigint;

-- Remove restrições NOT NULL de colunas antigas para compatibilidade total
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'solicitacoes' AND column_name = 'fk_servico_prof'
    ) THEN
        ALTER TABLE public.solicitacoes ALTER COLUMN fk_servico_prof DROP NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'solicitacoes' AND column_name = 'fk_endereco'
    ) THEN
        ALTER TABLE public.solicitacoes ALTER COLUMN fk_endereco DROP NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'solicitacoes' AND column_name = 'tipo_execucao'
    ) THEN
        ALTER TABLE public.solicitacoes ALTER COLUMN tipo_execucao DROP NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'solicitacoes' AND column_name = 'tipo_entrega'
    ) THEN
        ALTER TABLE public.solicitacoes ALTER COLUMN tipo_entrega DROP NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'solicitacoes' AND column_name = 'data_agendada'
    ) THEN
        ALTER TABLE public.solicitacoes ALTER COLUMN data_agendada DROP NOT NULL;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'solicitacoes' AND column_name = 'hora_agendada'
    ) THEN
        ALTER TABLE public.solicitacoes ALTER COLUMN hora_agendada DROP NOT NULL;
    END IF;
END $$;

-- Garante constraints de integridade para solicitacoes
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'solicitacoes_fk_usuario_fkey'
    ) THEN
        ALTER TABLE public.solicitacoes
            ADD CONSTRAINT solicitacoes_fk_usuario_fkey
            FOREIGN KEY (fk_usuario) REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'solicitacoes_fk_status_fkey'
    ) THEN
        ALTER TABLE public.solicitacoes
            ADD CONSTRAINT solicitacoes_fk_status_fkey
            FOREIGN KEY (fk_status) REFERENCES public.status(id_status);
    END IF;
END $$;

-- 4. Inserção de registro na tabela 'status' com enum 'Serviço' caso ainda não exista
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM public.status WHERE tipo_status::text = 'Serviço'
    ) THEN
        INSERT INTO public.status (tipo_status, status)
        VALUES ('Serviço'::"Tipo Status", 'Pendente');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        -- Fallback caso o enum tenha outro nome de tipo
        NULL;
END $$;

-- 5. Configuração de Row Level Security (RLS)
ALTER TABLE public.lista_servicos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ass_servicos_lista ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.solicitacoes ENABLE ROW LEVEL SECURITY;

-- Políticas para lista_servicos
DROP POLICY IF EXISTS "lista_servicos_all_cliente" ON public.lista_servicos;
CREATE POLICY "lista_servicos_all_cliente" ON public.lista_servicos
    FOR ALL TO authenticated
    USING (
        fk_usuario IN (
            SELECT id_usuario FROM public.usuarios WHERE auth_id = auth.uid()
        )
    )
    WITH CHECK (
        fk_usuario IN (
            SELECT id_usuario FROM public.usuarios WHERE auth_id = auth.uid()
        )
    );

-- Políticas para ass_servicos_lista
DROP POLICY IF EXISTS "ass_servicos_lista_all_cliente" ON public.ass_servicos_lista;
CREATE POLICY "ass_servicos_lista_all_cliente" ON public.ass_servicos_lista
    FOR ALL TO authenticated
    USING (
        fk_lista IN (
            SELECT id_lista FROM public.lista_servicos
            WHERE fk_usuario IN (
                SELECT id_usuario FROM public.usuarios WHERE auth_id = auth.uid()
            )
        )
    )
    WITH CHECK (
        fk_lista IN (
            SELECT id_lista FROM public.lista_servicos
            WHERE fk_usuario IN (
                SELECT id_usuario FROM public.usuarios WHERE auth_id = auth.uid()
            )
        )
    );

-- Atualiza política de INSERT na tabela solicitacoes para o cliente
DROP POLICY IF EXISTS "solicitacoes_insert_cliente" ON public.solicitacoes;
CREATE POLICY "solicitacoes_insert_cliente" ON public.solicitacoes
    FOR INSERT TO authenticated
    WITH CHECK (
        fk_usuario IN (
            SELECT id_usuario FROM public.usuarios WHERE auth_id = auth.uid()
        )
    );
